In [1]:
import pandas as pd

In [19]:
train=pd.read_csv('C:/Users/nithi/OneDrive - Lovely Professional University/CSM351/housing.csv/Hyderabad.csv')
train.head(10)

,Price,Area,Location,No. of Bedrooms,Resale,MaintenanceStaff,Gymnasium,SwimmingPool,LandscapedGardens,JoggingTrack,...,LiftAvailable,BED,VaastuCompliant,Microwave,GolfCourse,TV,DiningTable,Sofa,Wardrobe,Refrigerator
0,6968000,1340,Nizampet,2,0,0,1,1,1,1,...,1,0,1,0,0,0,0,0,0,0
1,29000000,3498,Hitech City,4,0,0,1,1,1,1,...,1,0,1,0,0,0,0,0,0,0
2,6590000,1318,Manikonda,2,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,5739000,1295,Alwal,3,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4,5679000,1145,Kukatpally,2,0,0,0,0,1,0,...,1,0,0,0,0,0,0,0,0,0
5,6099000,1230,Nizampet,2,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
6,7000000,1350,Manikonda,2,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
7,4198000,1400,Gachibowli,3,0,0,1,1,0,0,...,1,0,0,0,0,0,0,0,0,0
8,9900000,2240,Tellapur,3,0,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
9,9800000,1520,Gachibowli,2,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0

In [35]:
import numpy as np
np.random.seed(42)
data={
    'feature1':np.random.normal(50,10,100),
    'feature2':np.random.normal(30,5,100),
    'feature3':np.random.normal(100,20,100),
    'feature4':np.random.normal(10,2,100)
}
data['Target']= 0.3 * data['feature1'] + 0.5 *data['feature2'] + 0.2 * data['feature3'] + np.random.normal(0,5,100)
dt=pd.DataFrame(data)

In [40]:
dt.head()

    feature1   feature2    feature3   feature4     Target
0  54.967142  22.923146  107.155747   8.342010  41.410727
1  48.617357  27.896773  111.215691   8.879638  47.779857
2  56.476885  28.286427  121.661025  11.494587  55.444703
3  65.230299  25.988614  121.076041  11.220741  57.013508
4  47.658466  29.193571   72.446613   9.958197  41.133321